### ISSUE TITLE
wiser2 

### ISSUE THREAD

**Issue by SmartSystemsSA** [paulw11/homebridge-wiser#10]
Hi there 
We are a home automation company in South Africa.
We are trying to connect a hoobs to Wiser 2. It pulls everything though but you can turn it on in the hoobs but it does nothing on the wiser.

**Comment by paulw11** [comment]
What is a hoobs? Can you control the group addresses through the home app?

**Comment by SmartSystemsSA** [comment]
Hi there im going to attach some picture to better example myself.

We are using a device that runs on raspberry pie and allows us to install this homebridge for the wiser.

It pulls the lights though but when we try and active it the lights don’t work.

If you could help it would be amazing.





Nicholas Naude

 

Smart Systems - Head Office S.A. 

Tel:             +27(0) 31 7672544 
Mobile:       +27(0) 817564280 
Email:           <mailto:technical2@smartsystems.co.za> technical2@smartsystems.co.za

Address:     18 Churchill Road, Winston Park, 3610    P O Box 72, Gillitts, 3603

Website:      <http://www.smartsystems.co.za> www.smartsystems.co.za

                                                                                                               



 P   Save A Tree - Please Do Not Print This Email Unless You Really Need To 

                                                                                                                               

NOTICE
This message contains privileged and confidential information intended only for the person or entity to which it is addressed. Any review, re-transmission, dissemination,
copy or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient, is prohibited. If you received this
message in error, please notify the sender immediately by e-mail, facsimile or telephone and thereafter delete the material from any computer. Any views expressed in
this message are those of the individual sender, except where the sender specifically states them to be the view of the entity transmitting the message.
