### ISSUE TITLE
Use without homebridge

### ISSUE THREAD

**Issue by NovaGL** [paulw11/homebridge-wiser#3]
Hi,

Just wondering if you would make something similar that would work without homebridge.

Say just a node.js project. I just want something I can use with Alexa.

Any help would be great.

**Comment by paulw11** [comment]
`wiser.js` is independent of homebridge, so you should be able to work from that. You can create an instance of `Wiser` and then call `start` on that instance. It will emit a discovery complete event once the wiser project has been parsed.  You can then access the `wiserGroups` property to get the C-Bus groups. You can set a group's level and a group will emit a level change event when it's level changes.

**Comment by NovaGL** [comment]
Thanks. What information do I need from the tech to access wiser project

**Comment by paulw11** [comment]
You just need the same parameters that are in the homebridge confit file; the wiser address, port, username and password.

**Comment by NovaGL** [comment]
Great. Will let you know how I go.

**Comment by NovaGL** [comment]
Got it working with homebridge. So that works fine.

How would I go about passing a command say turn off kitchen lights without homebridge.

**Comment by paulw11** [comment]
The `wiserGroups` property of your `Wiser` object is a dictionary of `WiserGroup` objects.  The key is the C-Bus group address. You need to find the group address of the kitchen light and then use that to get the appropriate `WiserGroup` object.  You can then pass this group to the `setLevel` function of `Wiser` to set the group level.  You could also build some other dictionary of `wiserGroup` objects, say be `name`

**Comment by NovaGL** [comment]
Thanks so much but this is a bit beyond me. If it is not too much trouble could you give me a full example without personal information.

I am using the Wiser 2. It seems to crash sometimes but might just be me overloading it. Thats why I wanted to try it with just one switch.

**Comment by NovaGL** [comment]
Going to use node-cbus instead thanks anyway
