### ISSUE TITLE
[Wiser] Error parsing response: Error: Unclosed root tag Line: 0 Column: 1469

### ISSUE THREAD

**Issue by Chris-JL** [paulw11/homebridge-wiser#9]
According to the log file I periodically get the error:
"[Wiser] Error parsing response: Error: Unclosed root tag
Line: 0
Column: 1469"

This might (or not) be connected to two issues I constantly have: 1) systematically my homebridge gets wrong the status of several lights (oddly, the non-dimmable ones) that are connected to the Wiser hub; 2) the Wiser hub in my house can read and set the temperature of different rooms, but this information and function is not passed to home bridge.

Any help, would be greatly appreciated.

**Comment by cbaddah** [comment]
I get the same error messages with a basic setup. I.e. there is no temperature sensor. ![image](https://user-images.githubusercontent.com/16547592/113522019-d4c7aa00-95e0-11eb-9025-2b22344c0f47.png)

**Comment by paulw11** [comment]
Can you run Homebridge in debug mode?  That will provide more information, in particular it will provide your entire Wiser project XML file. If you can attach your home bridge debug log it will help a lot.

**Comment by thealphabonanza** [comment]
I have Wiser running on Homebridge on an Ubuntu machine and never received that error.
Today I have just installed Homebridge with the Wiser plugin on a Windows 10 box and have now started to get this error every hour on the hour.
The error only shows up on the Windows machine.
[homebridgexx.log](https://github.com/paulw11/homebridge-wiser/files/6642159/homebridgexx.log)


[37m[12/06/2021, 10:00:05 pm] [39m[36m[Wiser2][39m [90mReceived <ka cbus_connected="1" /> <cbus_event app="0x102" name="cbusPowerTotals" current_total_power="0.00" current_total_cost="0.00" current_total_power_hour="0.00" current_total_power_day="0.00" current_total_power_week="0.00" current_total_power_month="0.00" current_total_cost_hour="0.00" current_total_cost_day="0.00" current_total_cost_week="0.00" current_total_cost_month="0.00" predicted_total_power_hour="0.00" predicted_total_power_day="0.00" predicted_total_power_week="0.00" predicted_total_power_month="0.00" predicted_total_cost_hour="0.00" predicted_total_cost_day="0.00" predicted_total_cost_week="0.00" predicted_total_cost_month="0.00" /> <cbus_event app="0x102" name="cbusPowerHistoryTotals" hourly_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," daily_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," weekly_energy_totals="0.00,0.00,0.00,0.00," monthly_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," hourly_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," daily_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0[39m
[37m[12/06/2021, 10:00:05 pm] [39m[36m[Wiser2][39m [90m<response><ka cbus_connected="1" /> <cbus_event app="0x102" name="cbusPowerTotals" current_total_power="0.00" current_total_cost="0.00" current_total_power_hour="0.00" current_total_power_day="0.00" current_total_power_week="0.00" current_total_power_month="0.00" current_total_cost_hour="0.00" current_total_cost_day="0.00" current_total_cost_week="0.00" current_total_cost_month="0.00" predicted_total_power_hour="0.00" predicted_total_power_day="0.00" predicted_total_power_week="0.00" predicted_total_power_month="0.00" predicted_total_cost_hour="0.00" predicted_total_cost_day="0.00" predicted_total_cost_week="0.00" predicted_total_cost_month="0.00" /> <cbus_event app="0x102" name="cbusPowerHistoryTotals" hourly_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," daily_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," weekly_energy_totals="0.00,0.00,0.00,0.00," monthly_energy_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," hourly_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," daily_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0</response>[39m
[37m[12/06/2021, 10:00:05 pm] [39m[36m[Wiser2][39m [31mError parsing response - Error: Unclosed root tag[39m
[31mLine: 0[39m
[31mColumn: 1507[39m
[31mChar: [39m
[37m[12/06/2021, 10:00:05 pm] [39m[36m[Wiser2][39m [90mReceived .00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," weekly_cost_totals="0.00,0.00,0.00,0.00," monthly_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," current_total_power="0.00" current_total_cost="0.00" current_total_power_hour="0.00" current_total_power_day="0.00" current_total_power_week="0.00" current_total_power_month="0.00" current_total_cost_hour="0.00" current_total_cost_day="0.00" current_total_cost_week="0.00" current_total_cost_month="0.00" predicted_total_power_hour="0.00" predicted_total_power_day="0.00" predicted_total_power_week="0.00" predicted_total_power_month="0.00" predicted_total_cost_hour="0.00" predicted_total_cost_day="0.00" predicted_total_cost_week="0.00" predicted_total_cost_month="0.00" /> [39m
[37m[12/06/2021, 10:00:05 pm] [39m[36m[Wiser2][39m [90m<response>.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," weekly_cost_totals="0.00,0.00,0.00,0.00," monthly_cost_totals="0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00," current_total_power="0.00" current_total_cost="0.00" current_total_power_hour="0.00" current_total_power_day="0.00" current_total_power_week="0.00" current_total_power_month="0.00" current_total_cost_hour="0.00" current_total_cost_day="0.00" current_total_cost_week="0.00" current_total_cost_month="0.00" predicted_total_power_hour="0.00" predicted_total_power_day="0.00" predicted_total_power_week="0.00" predicted_total_power_month="0.00" predicted_total_cost_hour="0.00" predicted_total_cost_day="0.00" predicted_total_cost_week="0.00" predicted_total_cost_month="0.00" /> </response>[39m

**Comment by paulw11** [comment]
The Wiser uses a socket to emit events.  The events are XML and received by Homebridge-wiser using a stream.  In some cases a single network receive event does not contain an entire XML document due to buffering.  

An alternate XML parsing approach is required; stream based rather than document based.
